Cocktail.create(name: "mojito")
Cocktail.create(name: "cosmopolitan")
Cocktail.create(name: "moscule mule")

Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "lime")
Ingredient.create(name: "tonic")
Ingredient.create(name: "elderflower")
Ingredient.create(name: "ginger beer")
