Cocktail.create(name: "Moscule Mule")
Cocktail.create(name: "Cosmopolitan")

Ingredient.create(name: "rum")
Ingredient.create(name: "vodka")
Ingredient.create(name: "gin")
Ingredient.create(name: "slice of lime")
Ingredient.create(name: "tonic")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "soda water")
Ingredient.create(name: "sugar")
Ingredient.create(name: "cranberry juice")
Ingredient.create(name: "cointreau")
Ingredient.create(name: "ginger beer")
Ingredient.create(name: "lime juice")
